name: Build ZMK firmware
on:
  workflow_dispatch:
  push:
    paths:
      - "config/**/*"
      - "zephyr/**/*"
      - "boards/**/*"
      - "build.yaml"
  pull_request:
    paths:
      - "config/**/*"
      - "zephyr/**/*"
      - "boards/**/*"
      - "build.yaml"

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
