# Example for using the keymap-drawer ZMK user config workflow
name: Draw ZMK keymaps
on:
  workflow_dispatch: # can be triggered manually
  push: # automatically run on changes to following paths
    paths:
      - ".github/workflows/draw.yml"
      - "config/**/*.keymap"
      - "config/**/*.dtsi"
      - "config/**/*.h"
      - "config/**/*.conf"
      - "keymap_drawer.config.yaml"

jobs:
  draw:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Install keymap-drawer and west
        run: |
          pipx install keymap-drawer
          pipx install west
      - name: Fetch west modules
        run: |
          west init -l config
          west config manifest.project-filter " -zmk,-zephyr"
          west update --fetch-opt=--filter=tree:0
      - name: Parse keymap
        run: keymap -c ./keymap_drawer.config.yaml parse -z ./config/corne.keymap > draw/corne.yaml
      - name: Draw layers
        run: keymap -c ./keymap_drawer.config.yaml draw draw/corne.yaml -k "crkbd/rev1" -l "LAYOUT_split_3x6_3" --keys-only > ./draw/corne.svg
      - name: Draw combos
        run: keymap -c ./keymap_drawer.config.yaml draw draw/corne.yaml -k "crkbd/rev1" -l "LAYOUT_split_3x6_3" -s base --combos-only > ./draw/combos.svg
      - name: Commit drawings
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add draw/corne.svg draw/combos.svg draw/corne.yaml
          git diff --cached --quiet || (git commit --amend --no-edit && git push --force-with-lease)
